name: build

on:
  push:
  workflow_dispatch:

jobs:
  build-packages:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel

    steps:
      - name: Upgrade system
        run: |
          pacman-key --init
          pacman -Sy --noconfirm && pacman -S --needed --noconfirm archlinux-keyring
          pacman -Syu --noconfirm --needed reflector git ccache

          reflector > /etc/pacman.d/mirrorlist

          sed -i 's/!ccache/ccache/g' /etc/makepkg.conf

      - name: Create user
        run: |
          chmod -R a+rw .
          useradd arch -m -d /home/arch
          echo "arch ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          cd ~arch
          chmod -R a+rw .

      - uses: actions/cache/restore@v3
        with:
          path: /home/arch/.cache/ccache
          key: arch-ccache

      - name: Build packages
        run: |
          sudo --set-home --user=arch git clone https://aur.archlinux.org/llvm-git.git
          cd llvm-git
          sudo --set-home --user=arch makepkg --noconfirm --rmdeps -s --nocheck

      - uses: actions/cache/save@v3
        if: always()
        with:
          path: /home/arch/.cache/ccache
          key: arch-ccache

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: |
            */*.pkg.tar.zst
